---
slug: silikon-sinapsis
filename: silikon-sinapsis
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2015
uuid: d3711ea6-7cc3-4f61-a198-f3176c16a2fd
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
